name: "Warn on state changes"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Run statediff"
        uses: orijtech/statediff@main
        with:
          pull_request_url: "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}.patch"
